apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-epiz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-epiz
    app.kubernetes.io/part-of: tkrw-pr712-0075-0008-app
  name: devfile-sample-epiz
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-epiz
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-epiz
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0008-tenant/tkrw-pr712-0075-0008-app/devfile-sample-epiz@sha256:8223bb264a0fda9c224983391c266e0c859c94d894e5a66ddd9597a6cc7a78cd
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
