apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-epiz
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0008-tenant/tkrw-pr712-0075-0008-app/devfile-sample-epiz@sha256:8223bb264a0fda9c224983391c266e0c859c94d894e5a66ddd9597a6cc7a78cd
        name: my-nodejs
        resources: {}
status: {}
